disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Blowfish"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   name = "Robert Bry≈õkiewicz"
   email = "robert@bryskiewicz.dev"
   image = "img/blowfish_logo.png"
   imageQuality = 96
   headline = "data engineer, wannabe game dev, cat lover"
   bio = ""
   links = [
     { email = "mailto:hello@your_domain.com" },
     { github = "https://github.com/username" },
     { itch-io = "https://username.itch.io" },
     { linkedin = "https://linkedin.com/in/username" },
     { medium = "https://medium.com/username" },
     { youtube = "https://youtube.com/username" },
   ]
